language: node_js
node_js:
- node
notifications:
  slack:
    secure: X/r8fc/kl0sG0u5/MaX90M8aDcjYNELBQA3V4ePH5nYH88Vp0+DrALJxiaskcMzScq1sxCz77e+eldfNfIwoMwqOg5EZ9qqoauz1XBEUAV149Oy5SIsDfcJ4LO6FxJcWZyJiowVooGspX32BQTa6sTUAYDs9Q9uryDqdBn3KztR2lSB6ff1rsS9EeeufjnDt2/SV2KeznOCpgxU0nkRCWGCUsb4FMNrWSW8fByKUcFeN8dA8lt/U1RmHixIWrhSPuNXHZ2S5hoNqZgsMfvC3hvtPBw/OZBHwKoVUWwXT/nTmx60OvNxqVVVQDO/ih/NwoZoMnWO/P1peGvrlpPALfLDbRECiihUV4H5z5L3cnKhDxEZH5zsIJj+J8rhfo2GJd0RRwUsxmrUIugkXhwiyTlhY7zvz9eChBhh95AEiBz1BHKs3X8WxvdHadEHzS/H9lcgoT/3BSMLp0eru2+aSykjz3Q0rp89aN8pqGT9En25d5H7MtRGEEjb0uOQebB6QJojzwyWSbF5+l6fIvgVJZDxFoLbCRRloXRHiidZ+j1AJid+chFje/Q4ueCCHhf5Ce6lsprC4NSHyHdjHKAdpM5wVXClnGJhN73ezNdWf0jYk7ZEbY8MnLgv0Od3GK9mjKaqlj2HyEFnNIRwkmhDyDaHrkIDgSZkpSw8L5f1c7k0=
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_c7d1ea4c11f1_key -iv $encrypted_c7d1ea4c11f1_iv
  -in secrets.yml.enc -out secrets.yml -d
- npm install -g serverless
script:
- npm install
- npm run test
- npm run build
- sls deploy -s prod
env:
  global:
    secure: vw6+MQCvHi8R78ECDf65l/pTAe9kv1LdhjXy58GJngn/6frJrMboQBSE9SoHtJEgjhA1clytka9VMed+/XNczHDRZmtCI4sMIGOWinGFY+mYrjtMWEQHeL86tSii5ANCVTrOyO/kIYuT3z+GkVROQS+ydLWwKqUFS4Z9Xbb6i04V4YOvZu/d+Zw2VsZyshoS8FDqD56VCqsFJ6Ua1VODIvoLsBvQm24iHphzBqNXzbOrwUG5jyVLu10uvlDY8Zoj/HqXv+L5OrMXqUT2fpH6u9glOGL68Nq3eq7NsEdtT3P8aD8NKUHWpB81GWCM6k+HUQ6ffTsqXYySb+JPifKCtx3veGrWQJ4vl9eW+H6UWZLVz1pP0fh1px9I8WKAooucaM7/trh83iHoCt7Divww8uG9Bnby5HAXXMzpy/rajS6AYCdBTvul3r53F6px+UT1/81OH5QWbvxD3keBUo2lBVslFfJoV7b8r4zilpdGa3JfJbPO1bemltyPP0jUJC6xsa1D1h8j/xdRbAlvbc/03YlH9ideckWNIyRGNzME1uHPnPZx6FqzYe1dZy5bLjjeVuCANAJ2MS2JKJgSrFQtvZteKqyomaqkV63/78be64usgZmrK2NYDrmPgA5lOeUcwgUo2KrxiQQAeJ7KocigcZzwDmRewgYeuD5q6YKwM9s=
